server:
  workers: 2
  config:
    memory:
      heapSize: "4G"
    query:
      maxMemory: "3GB"
      maxMemoryPerNode: "1GB"

additionalCatalogs:
  iceberg: |-
    connector.name=iceberg
    iceberg.jdbc-catalog.driver=org.postgresql.Driver
    iceberg.jdbc-catalog.url=jdbc:postgresql://postgres-service.metastore:5432/hivemetastore
    iceberg.jdbc-catalog.username=metastore
    iceberg.jdbc-catalog.password=password
    iceberg.catalog-impl=org.apache.iceberg.jdbc.JdbcCatalog
    iceberg.warehouse=s3a://iceberg/warehouse/
    iceberg.s3.endpoint=http://minio.minio-system.svc.cluster.local:9000
    iceberg.s3.access-key=minio
    iceberg.s3.secret-key=minio123
    iceberg.s3.path-style-access=true
  delta: |-
    connector.name=delta_lake
    hive.metastore.uri=thrift://hive-service.metastore:9083
    hive.s3.endpoint=http://minio-service.metastore:9000
    hive.s3.path-style-access=true
    hive.s3.aws-access-key=minio
    hive.s3.aws-secret-key=minio123
    delta.enable-non-concurrent-writes=true
  rdbms: |-
    connector.name=postgresql
    connection-url=jdbc:postgresql://postgres-service.metastore:5432/hivemetastore
    connection-user=metastore
    connection-password=password
