server:
  workers: 2
  config:
    memory:
      heapSize: "4G"
    query:
      maxMemory: "3GB"
      maxMemoryPerNode: "1GB"

additionalCatalogs:
  lakehouse: |
    connector.name=iceberg
    hive.metastore.uri=thrift://hive-metastore.metastore.svc.cluster.local:9083
    hive.s3.path-style-access=true
    hive.s3.endpoint=http://172.18.0.2:30481
    hive.s3.aws-access-key=minio
    hive.s3.aws-secret-key=minio123
    iceberg.register-table-procedure.enabled=true
    iceberg.unique-table-location=true
    iceberg.hive-catalog-name=minio
  minio: |
    connector.name=hive
    hive.metastore.uri=thrift://hive-metastore.metastore.svc.cluster.local:9083
    hive.s3.path-style-access=true
    hive.s3.endpoint=http://172.18.0.2:30481
    hive.s3.aws-access-key=minio
    hive.s3.aws-secret-key=minio123
    hive.metastore.thrift.client.connect-timeout=3m
    hive.metastore.thrift.client.read-timeout=3m
    hive.s3.connect-timeout=3m
    hive.s3.socket-timeout=3m
    hive.non-managed-table-writes-enabled=true
    hive.storage-format=ORC
    hive.partition-projection-enabled=true
  postgresql: |
    connector.name=postgresql
    connection-url=jdbc:postgresql://postgres.data-source.svc.cluster.local:5432/data_engineer
    connection-user=data_engineer
    connection-password=password
