server:
  workers: 2
  config:
    memory:
      heapSize: "4G"
    query:
      maxMemory: "3GB"
      maxMemoryPerNode: "1GB"

additionalCatalogs:
  iceberg.properties: |-
    connector.name=iceberg
    iceberg.catalog.type=jdbc
    iceberg.jdbc-url=jdbc:postgresql://postgres-service.metastore:5432/hivemetastore
    iceberg.jdbc-user=metastore
    iceberg.jdbc-password=password
    iceberg.jdbc-catalog-name=iceberg_catalog
    iceberg.jdbc-warehouse-dir=s3a://iceberg/warehouse/
    iceberg.s3.endpoint=http://minio.minio-system.svc.cluster.local:9000
    iceberg.s3.access-key=minio
    iceberg.s3.secret-key=minio123
    iceberg.s3.path-style-access=true
