server:
  workers: 2
  config:
    memory:
      heapSize: "4G"
    query:
      maxMemory: "3GB"
      maxMemoryPerNode: "1GB"

additionalCatalogs:
  iceberg.properties: |-
    # Nome do conector
    connector.name=iceberg

    # Configurações do catálogo JDBC do Iceberg
    iceberg.catalog.type=jdbc
    iceberg.catalog.jdbc.driver=org.postgresql.Driver
    iceberg.catalog.jdbc.url=jdbc:postgresql://postgres-service.metastore:5432/hivemetastore
    iceberg.catalog.jdbc.username=metastore
    iceberg.catalog.jdbc.password=password
    iceberg.catalog.warehouse=s3a://iceberg/warehouse/

    # Configurações do S3 (Minio)
    iceberg.catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO
    iceberg.s3.access-key=minio
    iceberg.s3.secret-key=minio123
    iceberg.s3.endpoint=http://minio.minio-system.svc.cluster.local:9000
    iceberg.s3.path-style-access=true
